// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vidulum/verify/external_address.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ExternalAddress struct {
	Vidulum  string `protobuf:"bytes,1,opt,name=vidulum,proto3" json:"vidulum,omitempty"`
	Bitcoin  string `protobuf:"bytes,2,opt,name=bitcoin,proto3" json:"bitcoin,omitempty"`
	Ethereum string `protobuf:"bytes,3,opt,name=ethereum,proto3" json:"ethereum,omitempty"`
	Solana   string `protobuf:"bytes,4,opt,name=solana,proto3" json:"solana,omitempty"`
	Zcash    string `protobuf:"bytes,5,opt,name=zcash,proto3" json:"zcash,omitempty"`
}

func (m *ExternalAddress) Reset()         { *m = ExternalAddress{} }
func (m *ExternalAddress) String() string { return proto.CompactTextString(m) }
func (*ExternalAddress) ProtoMessage()    {}
func (*ExternalAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbe5997a3446bcd, []int{0}
}
func (m *ExternalAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExternalAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExternalAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExternalAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalAddress.Merge(m, src)
}
func (m *ExternalAddress) XXX_Size() int {
	return m.Size()
}
func (m *ExternalAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalAddress proto.InternalMessageInfo

func (m *ExternalAddress) GetVidulum() string {
	if m != nil {
		return m.Vidulum
	}
	return ""
}

func (m *ExternalAddress) GetBitcoin() string {
	if m != nil {
		return m.Bitcoin
	}
	return ""
}

func (m *ExternalAddress) GetEthereum() string {
	if m != nil {
		return m.Ethereum
	}
	return ""
}

func (m *ExternalAddress) GetSolana() string {
	if m != nil {
		return m.Solana
	}
	return ""
}

func (m *ExternalAddress) GetZcash() string {
	if m != nil {
		return m.Zcash
	}
	return ""
}

func init() {
	proto.RegisterType((*ExternalAddress)(nil), "vidulum.verify.ExternalAddress")
}

func init() {
	proto.RegisterFile("vidulum/verify/external_address.proto", fileDescriptor_0fbe5997a3446bcd)
}

var fileDescriptor_0fbe5997a3446bcd = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0xcb, 0x4c, 0x29,
	0xcd, 0x29, 0xcd, 0xd5, 0x2f, 0x4b, 0x2d, 0xca, 0x4c, 0xab, 0xd4, 0x4f, 0xad, 0x28, 0x49, 0x2d,
	0xca, 0x4b, 0xcc, 0x89, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x83, 0x2a, 0xd3, 0x83, 0x28, 0x53, 0xea, 0x67, 0xe4, 0xe2, 0x77, 0x85, 0x2a,
	0x75, 0x84, 0xa8, 0x14, 0x92, 0xe0, 0x62, 0x87, 0xaa, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x41, 0x32, 0x49, 0x99, 0x25, 0xc9, 0xf9, 0x99, 0x79, 0x12, 0x4c, 0x10, 0x19, 0x28,
	0x57, 0x48, 0x8a, 0x8b, 0x23, 0xb5, 0x24, 0x23, 0xb5, 0x28, 0xb5, 0x34, 0x57, 0x82, 0x19, 0x2c,
	0x05, 0xe7, 0x0b, 0x89, 0x71, 0xb1, 0x15, 0xe7, 0xe7, 0x24, 0xe6, 0x25, 0x4a, 0xb0, 0x80, 0x65,
	0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0xaa, 0xe4, 0xc4, 0xe2, 0x0c, 0x09, 0x56, 0xb0, 0x30, 0x84,
	0xe3, 0x64, 0x70, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e,
	0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x62, 0x30, 0x2f,
	0x56, 0xc0, 0x3c, 0x59, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xf6, 0x9a, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x64, 0x2b, 0x9b, 0x1a, 0x03, 0x01, 0x00, 0x00,
}

func (m *ExternalAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExternalAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExternalAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Zcash) > 0 {
		i -= len(m.Zcash)
		copy(dAtA[i:], m.Zcash)
		i = encodeVarintExternalAddress(dAtA, i, uint64(len(m.Zcash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Solana) > 0 {
		i -= len(m.Solana)
		copy(dAtA[i:], m.Solana)
		i = encodeVarintExternalAddress(dAtA, i, uint64(len(m.Solana)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Ethereum) > 0 {
		i -= len(m.Ethereum)
		copy(dAtA[i:], m.Ethereum)
		i = encodeVarintExternalAddress(dAtA, i, uint64(len(m.Ethereum)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Bitcoin) > 0 {
		i -= len(m.Bitcoin)
		copy(dAtA[i:], m.Bitcoin)
		i = encodeVarintExternalAddress(dAtA, i, uint64(len(m.Bitcoin)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vidulum) > 0 {
		i -= len(m.Vidulum)
		copy(dAtA[i:], m.Vidulum)
		i = encodeVarintExternalAddress(dAtA, i, uint64(len(m.Vidulum)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintExternalAddress(dAtA []byte, offset int, v uint64) int {
	offset -= sovExternalAddress(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ExternalAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Vidulum)
	if l > 0 {
		n += 1 + l + sovExternalAddress(uint64(l))
	}
	l = len(m.Bitcoin)
	if l > 0 {
		n += 1 + l + sovExternalAddress(uint64(l))
	}
	l = len(m.Ethereum)
	if l > 0 {
		n += 1 + l + sovExternalAddress(uint64(l))
	}
	l = len(m.Solana)
	if l > 0 {
		n += 1 + l + sovExternalAddress(uint64(l))
	}
	l = len(m.Zcash)
	if l > 0 {
		n += 1 + l + sovExternalAddress(uint64(l))
	}
	return n
}

func sovExternalAddress(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExternalAddress(x uint64) (n int) {
	return sovExternalAddress(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ExternalAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExternalAddress
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExternalAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExternalAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vidulum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExternalAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vidulum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bitcoin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExternalAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bitcoin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ethereum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExternalAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ethereum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solana", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExternalAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Solana = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zcash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExternalAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Zcash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExternalAddress(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExternalAddress
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExternalAddress(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExternalAddress
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExternalAddress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExternalAddress
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExternalAddress
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExternalAddress
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExternalAddress        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExternalAddress          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExternalAddress = fmt.Errorf("proto: unexpected end of group")
)
